//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int proId { get; set; }
        public string proName { get; set; }
        public Nullable<int> catId { get; set; }
        public string proPhoto { get; set; }
        public Nullable<int> price { get; set; }
        public string origin { get; set; }
        public string avialableForSell { get; set; }
    }
}
